### ISSUE TITLE
DB Package Import - Not found

### ISSUE THREAD

**Issue by christianledgard** [nramkissoon/NPM-TurboRepo-tRPC-Next.js-NextAuth-Prisma-PlanetScale-Starter#1]
Hi,
When importing the `"db"` package from `apps/web/src/backend/clients/prisma.ts`, the package is not recognized:

<img width="989" alt="Screen Shot 2022-05-11 at 23 32 29" src="https://user-images.githubusercontent.com/39962750/167992888-39d0d824-8257-4a88-a8a9-642f79f576e2.png">
 
I verified if the error persisted across other packages, but it seems that the issue is on the template. For example, reviewing the [official example](https://github.com/vercel/turborepo/tree/main/examples/basic) from the Monoturbo web page, the `"ui"` package is recognized correctly:

<img width="655" alt="Screen Shot 2022-05-11 at 23 33 12" src="https://user-images.githubusercontent.com/39962750/167993217-a459bf96-3d04-44b0-ab93-06a3bf3fbbbb.png">

Thanks for the help.

**Comment by nramkissoon** [comment]
Hey thanks for bringing this up. 

I tested this on a fresh clone. After running npm install in the root I ran into the same problem you described. 

I fixed it by building all the packages (this will also generate the Prisma client) and reloading my VSCode window. LMK if this helps.

**Comment by christianledgard** [comment]
Building the `db` package and reloading the VSCode window fixed the issue. Thank you for the help!
